export const ALERT_NOTIFICATION = Symbol('ALERT_NOTIFICATION');

export const APPLICATION_RETRIEVAL_LOADING = Symbol('APPLICATION_RETRIEVAL_LOADING');
export const APPLICATION_RETRIEVAL_SUCCESS = Symbol('APPLICATION_RETRIEVAL_SUCCESS');
export const APPLICATION_RETRIEVAL_FAILURE = Symbol('APPLICATION_RETRIEVAL_FAILURE');

export const INSTANCE_CREATING = Symbol('INSTANCE_CREATING');
export const INSTANCE_SUCCESS = Symbol('INSTANCE_SUCCESS');
export const INSTANCE_FAILURE = Symbol('INSTANCE_FAILURE');
export const INSTANCE_DELETION_SUCCESS = Symbol('INSTANCE_DELETION_SUCCESS');
export const INSTANCE_DELETION_FAILURE = Symbol('INSTANCE_DELETION_FAILURE');

export const OBJECT_RETRIEVAL_LOADING = Symbol('OBJECT_RETRIEVAL_LOADING');
export const OBJECT_RETRIEVAL_SUCCESS = Symbol('OBJECT_RETRIEVAL_SUCCESS');
export const OBJECT_RETRIEVAL_FAILURE = Symbol('OBJECT_RETRIEVAL_FAILURE');